name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ${{ matrix.operating_systems }}

    strategy:
      matrix:
        operating_systems: [windows-latest, ubuntu-latest, macos-latest]
        node-version: [20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run the tests
      run: npm test

    - name: Fetch all branches
      run: git fetch --all

    - name: Merge branch to master if tests pass
      if: success() && github.ref != 'refs/heads/master'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git checkout master
        git merge --no-ff origin/${{ github.head_ref }} -m "Merge branch ${{ github.head_ref }} into master"
        git push origin master
      env:
        ACTIONS_GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

    - name: Build
      run: npm run build

    - name: Deploy
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        npm run deploy
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}

  docker-build:
    needs: build
    runs-on: ubuntu-latest  # Only run the Docker build on Ubuntu

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWD_TOKEN }}

    - name: Build and push Docker image
      run: |
        IMAGE_NAME="${{ github.repository }}"
        LOWERCASE_IMAGE_NAME=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')
        COMMIT_SHA="${{ github.sha }}"
        TAG="${LOWERCASE_IMAGE_NAME}:${COMMIT_SHA::7}"
        docker buildx build --tag $TAG --push .
